services:

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    environment:
      - backendUrl=http://backend:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
